#$$$$$$$\                                           $$$$$$\
#$$  __$$\                                         $$  __$$\
#$$ |  $$ | $$$$$$$\ $$\   $$\  $$$$$$$\  $$$$$$\  $$ /  \__|$$$$$$\  $$\   $$\
#$$$$$$$  |$$  _____|$$ |  $$ |$$  _____|$$  __$$\ $$$$\    $$  __$$\ $$ |  $$ |
#$$  ____/ \$$$$$$\  $$ |  $$ |$$ /      $$ /  $$ |$$  _|   $$$$$$$$ |$$ |  $$ |
#$$ |       \____$$\ $$ |  $$ |$$ |      $$ |  $$ |$$ |     $$   ____|$$ |  $$ |
#$$ |      $$$$$$$  |\$$$$$$$ |\$$$$$$$\ \$$$$$$  |$$ |     \$$$$$$$\ \$$$$$$  |
#\__|      \_______/  \____$$ | \_______| \______/ \__|      \_______| \______/
#                    $$\   $$ |
#                    \$$$$$$  |
#                     \______/
# https://discord.gg/vanillamcbe
# https://github.com/psycofeu


discord_description: "Get discord server"
discord_message: "§9- §fHere the discord server : §9https://discord.gg/vanillamcbe" #Change discord